import os
import sys
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.documents import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains.retrieval import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

# --- 1. HANA DB Imports (Mandatory Dependencies) ---

try:
    # 1a. LangChain integration for SAP HANA
    # Requires: pip install langchain-hanadb
    from langchain_community.vectorstores import HanaDB
    
    # 1b. SAP HANA Python Driver
    # Requires: pip install hdbcli
    from hdbcli import dbapi as hana_db_api

except ImportError as e:
    print(f"FATAL ERROR: Missing required library. Please install the necessary packages.")
    print(f"Error details: {e}")
    print("\nInstallation instructions:")
    print("pip install hdbcli langchain-community langchain-openai")
    # Exit gracefully if key dependencies are missing
    sys.exit(1)


# --- 2. Configuration (Reads from your .env or environment) ---

# Check for API Key
if not os.environ.get("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY environment variable not set.")

# SAP HANA Connection Details
HANA_HOST = os.environ.get("HANA_HOST")
HANA_PORT = os.environ.get("HANA_PORT")
HANA_USER = os.environ.get("HANA_USER")
HANA_PASSWORD = os.environ.get("HANA_PASSWORD")
HANA_SCHEMA = os.environ.get("HANA_SCHEMA", "RAG_SCHEMA")
HANA_TABLE_NAME = "LANGCHAIN_DOCS"

if not all([HANA_HOST, HANA_PORT, HANA_USER, HANA_PASSWORD]):
    raise ValueError("One or more HANA credential environment variables (HANA_HOST, HANA_PORT, HANA_USER, HANA_PASSWORD) are not set.")

# --- 3. Initialization ---

# Embeddings Model (Dimension is 1536 for text-embedding-3-small)
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
# LLM
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)


def setup_hana_connection():
    """Establishes and returns the connection object to SAP HANA."""
    conn = None
    try:
        # Connect to SAP HANA using the standard hdbcli driver
        print(f"Attempting to connect to HANA at {HANA_HOST}:{HANA_PORT}...")
        conn = hana_db_api.connect(
            address=HANA_HOST, 
            port=int(HANA_PORT), 
            user=HANA_USER, 
            password=HANA_PASSWORD
        )
        print("HANA Connection successful.")
        return conn
    except Exception as e:
        print(f"Error connecting to HANA: {e}")
        # Re-raise the exception to stop execution if connection fails
        raise

def create_vector_table(connection, table_name, vector_dimension=1536):
    """Creates the necessary vector table in the specified HANA schema."""
    cursor = None
    try:
        cursor = connection.cursor()
        
        # 1. Define the SQL DDL for the vector table
        # We ensure the table is created in the specified schema
        full_table_name = f'"{HANA_SCHEMA}"."{table_name}"'
        
        # The REAL_VECTOR data type is critical for the vector embedding column
        ddl_sql = f"""
        CREATE TABLE {full_table_name} (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TEXT_CONTENT NCLOB,
            VECTOR_EMBEDDING REAL_VECTOR({vector_dimension}),
            METADATA NCLOB
        );
        """
        
        # 2. Execute the SQL
        print(f"\n--- Creating Vector Table: {full_table_name} ---")
        cursor.execute(ddl_sql)
        connection.commit()
        print("Vector table created successfully.")
        
    except hana_db_api.Error as e:
        # Catch common error if table already exists
        if "already exists" in str(e):
            print(f"Warning: Table {full_table_name} already exists. Skipping creation.")
        else:
            print(f"Error executing DDL: {e}")
            raise
    finally:
        if cursor:
            cursor.close()


def load_and_index_data(documents: list[Document], table_name: str, connection, embedding_model):
    """
    Splits documents, embeds them, and stores them in the SAP HANA Vector Store.
    """
    print("\n--- Starting Data Indexing Process ---")
    
    # 1. Define and apply text splitter
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )
    split_documents = text_splitter.split_documents(documents)
    print(f"Split {len(documents)} document(s) into {len(split_documents)} chunks.")

    # 2. Create the HanaDB vector store and populate it
    # This calls the HanaDB API to connect, embed, and insert data
    vector_store = HanaDB.from_documents(
        documents=split_documents,
        embedding=embedding_model,
        connection=connection,
        table_name=table_name,
        # Required to tell HanaDB which schema to use
        schema=HANA_SCHEMA
    )
    
    print("--- Data Indexing Complete ---")
    return vector_store

def run_rag_query(vector_store, query: str):
    """
    Defines and executes the RAG chain.
    """
    print(f"\n--- Running RAG Query: '{query}' ---")
    
    # 1. Define the Retrieval Chain Prompt
    system_prompt = (
        "You are an expert Q&A assistant for SAP HANA. Use the following context "
        "to answer the user's question concisely and accurately. If the context "
        "does not contain the answer, state that you cannot find the relevant information."
        "\n\nContext: {context}"
    )
    
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system_prompt),
            ("human", "{input}"),
        ]
    )

    # 2. Define the Document Combining Chain
    document_chain = create_stuff_documents_chain(llm, prompt)

    # 3. Define the Retriever
    # HanaDB.as_retriever() uses the underlying HANA vector search capabilities
    retriever = vector_store.as_retriever(search_kwargs={"k": 2})

    # 4. Create the main Retrieval Chain
    retrieval_chain = create_retrieval_chain(retriever, document_chain)
    
    # 5. Invoke the Chain
    response = retrieval_chain.invoke({"input": query})
    
    print("\n--- RAG Response ---")
    print("Query:", query)
    print("\nAnswer:\n" + response["answer"])
    
    # Display the source documents retrieved from HANA
    retrieved_docs = response.get('context', [])
    print("\n--- Retrieved Contexts (from HANA) ---")
    if retrieved_docs:
        for i, doc in enumerate(retrieved_docs):
            print(f"[{i+1}] Source: {doc.metadata.get('source', 'N/A')}")
            print(f"    Content Preview: {doc.page_content[:100]}...")
    else:
        print("No documents were retrieved.")
    print("------------------------")


if __name__ == "__main__":
    
    # 0. Define Mock Data (Replace with your actual document loading logic)
    sample_documents = [
        Document(
            page_content="""
            SAP HANA is a modern data platform designed for real-time analytics and application development. 
            The SAP HANA Cloud Vector Engine stores vectors (embeddings) and performs vector search 
            operations, such as k-nearest neighbor (KNN) search and radius search, directly within the database. 
            It is a core component for deploying enterprise RAG applications on a reliable foundation.
            """,
            metadata={"source": "hana_rag_whitepaper.pdf"}
        ),
        Document(
            page_content="""
            LangChain is an open-source framework designed to simplify the creation of applications 
            using large language models (LLMs). It provides tools for chaining LLM calls, managing 
            prompts, and integrating with external data sources like vector databases, databases, and APIs.
            This framework facilitates the entire RAG pipeline from ingestion to final generation.
            """,
            metadata={"source": "langchain_overview.txt"}
        ),
    ]

    # 1. Connect to SAP HANA
    hana_conn = setup_hana_connection()

    # 2. MANDATORY STEP: Create the vector table structure
    # This is done using the direct DB connection before LangChain uses it for insertion
    create_vector_table(
        connection=hana_conn,
        table_name=HANA_TABLE_NAME,
        vector_dimension=1536
    )

    # 3. Index the data into SAP HANA
    hana_vector_store = load_and_index_data(
        documents=sample_documents,
        table_name=HANA_TABLE_NAME,
        connection=hana_conn,
        embedding_model=embeddings
    )
    
    # 4. Run the RAG query
    user_query = "What is the key benefit of using the SAP HANA Vector Engine for RAG?"
    run_rag_query(hana_vector_store, user_query)
    
    # 5. Close the connection
    if hana_conn:
        hana_conn.close()
        print("\nHANA Connection successfully closed.")
